def on_up_pressed():
    if My_player.vy == 0:
        My_player.vy = -155
controller.up.on_event(ControllerButtonEvent.PRESSED, on_up_pressed)

def makelevel():
    if level == 1:
        tiles.set_current_tilemap(tilemap("""
            level1
        """))
        tiles.place_on_tile(My_player, tiles.get_tile_location(10, 1))
    elif level == 2:
        tiles.set_current_tilemap(tilemap("""
            level3
        """))
        tiles.place_on_tile(My_player, tiles.get_tile_location(0, 16))
    elif level == 3:
        tiles.set_current_tilemap(tilemap("""
            level10
        """))
        tiles.place_on_tile(My_player, tiles.get_tile_location(0, 16))
    else:
        game.set_game_over_effect(True, effects.confetti)
def createLevel():
    pass

def on_overlap_tile(sprite, location):
    game.game_over(False)
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.hazard_lava0,
    on_overlap_tile)

def on_overlap_tile2(sprite2, location2):
    global level
    level += 1
    makelevel()
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.collectible_red_crystal,
    on_overlap_tile2)

level = 0
My_player: Sprite = None
scene.set_background_color(15)
My_player = sprites.create(img("""
        ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111ffff.....
            ......fffcdb1bc111cf....
            ....fc111cbfbf1b1b1f....
            ....f1b1b1ffffbfbfbf....
            ....fbfbfffffff.........
            .........fffff..........
            ..........fff...........
            ........................
            ........................
            ........................
            ........................
    """),
    SpriteKind.player)
controller.move_sprite(My_player, 100, 0)
My_player.ay = 350
scene.camera_follow_sprite(My_player)
level = 1
makelevel()